### ISSUE TITLE
mockgen not found in PATH

### ISSUE THREAD

**Issue by colonwq** [test-network-function/test-network-function#215]
The makefile calls mockgen from the go package directory without updating PATH to include the GOBIN directory.

Need to update the Makefile to prepend PATH=${PATH}:${GOBIN} to all calls to mockgen. [Example](https://github.com/test-network-function/test-network-function/blob/a05750a40cce99dc154e79197ff57430377f786d/Makefile#L113) line.

**Comment by AbhishekBandarupalle** [comment]
I had similar errors when trying to setup a new environment, 
makefile did not set the PATH env variable for mockgen. Did something like this: 
`export GOPATH="$HOME/go"
PATH="$GOPATH/bin:$PATH"`

**Comment by ryandgoulding** [comment]
This must be set manually, and is documented in mockgen's README.md https://github.com/golang/mock#installation and by us in [README.md](https://github.com/test-network-function/test-network-function#dependencies).

Essentially, setting `GOPATH` and `PATH` is installation specific.  In fact, we have to set these manually in our own `Dockerfile`.  See:

https://github.com/test-network-function/test-network-function/blob/main/Dockerfile#L22
https://github.com/test-network-function/test-network-function/blob/main/Dockerfile#L32

In our containerized offering, we automatically set all of this, as you can see above.  This is a limitation of `mockgen`, not our test suite, so I am closing this issue.
