### ISSUE TITLE
Container tests - ROOT_CHECK test fails even using a non-root pod

### ISSUE THREAD

**Issue by ramperher** [test-network-function/test-network-function#281]
It has been detected, while testing the CNF Cert Suite on DCI, that the ROOT_CHECK test from the Container test suite is failing even though a non-root pod is being used.

Specifically, the pod under test is the following from the cnf-certification-test-partner repo: [local-pod-under-test.yaml](https://github.com/test-network-function/cnf-certification-test-partner/blob/main/local-test-infra/local-pod-under-test.yaml), only changing the number of replicas from 2 to 1.

What has been discovered is that, if using a Pod instead of a Deployment, the ROOT_CHECK test passes, as `oc get pod <podName> -n <nsName> -o json  | jq -r '.spec.containers[0].securityContext.runAsUser` returns `null`, but when using a Deployment, it returns `1000640000` (i.e. the user ID that is being used, which is non-root because it is different than 0).

Exact output of one example of execution with this failure present:

```
container when under test is running test for : test-cnf/test-7cd9f7f9d4-xjcpz for test command :  ROOT_CHECK`
    /var/lib/dci-openshift-app-agent/test_network_function/test-network-function/container/suite.go:162`
  2021/07/22 08:20:34 Sent: "oc get pod test-7cd9f7f9d4-xjcpz -n test-cnf -o json  | jq -r '.spec.containers[0].securityContext.runAsUser' && echo END_OF_TEST_SENTINEL\n"
  2021/07/22 08:20:34 Match for RE: ".+((.|\n)*END_OF_TEST_SENTINEL\n)" found: ["1000690000\nEND_OF_TEST_SENTINEL\n" "\nEND_OF_TEST_SENTINEL\n" "\n"] Buffer: "1000690000\nEND_OF_TEST_SENTINEL\n"

• Failure [0.303 seconds]
container
/var/lib/dci-openshift-app-agent/test_network_function/test-network-function/container/suite.go:60
  when under test
  /var/lib/dci-openshift-app-agent/test_network_function/test-network-function/container/suite.go:92
    is running test for : test-cnf/test-7cd9f7f9d4-xjcpz for test command :  ROOT_CHECK [It]
    /var/lib/dci-openshift-app-agent/test_network_function/test-network-function/container/suite.go:162

    Expected
        <int>: 0
    to equal
        <int>: 1

    /var/lib/dci-openshift-app-agent/test_network_function/test-network-function/container/suite.go:186
```

According to what it is commented in [CNFCERT-62](https://issues.redhat.com/browse/CNFCERT-62), it seems that the pattern used for this checking is not working properly, as it should only fail if the user is exactly 0.

**Comment by jun-rh** [comment]
The fix is merged into the main branch. If running container, use quay.io/testnetworkfunction/test-network-function:unstable
