### ISSUE TITLE
./run-tnf-container.sh always deploys cnf-certification-test-partner pod in default namespace

### ISSUE THREAD

**Issue by AbhishekBandarupalle** [test-network-function/test-network-function#507]
The script `./run-tnf-container.sh` always deploys `partner` pod in default namespace, which causes the pod to always be attached to default ovn-kubernetes CNI and hence the test **Multus Overlay Network Testing network connectivity** fails or is skipped.

**Comment by hamadise** [comment]
The **partner** pods should be attached to the created **multus** network so it can be used to ping the Pods Under Test.
When attached to default network only, it will test connectivity to PODs in default ovn-k8s

**Comment by AbhishekBandarupalle** [comment]
That's right. I did that manually by adding the k8s.v1.cni.cncf.io/networks to partner pod deploy yaml. 
But when using the .`/run-tnf-container.sh` it doesn't automatically deploy the partner pod in the namespace where multus is defined (which is the pod under test namespace) 
Would eliminate manually deploying partner pod if that is done in the script
