### ISSUE TITLE
catalog generator no longer keeps the suites in order

### ISSUE THREAD

**Issue by jun-rh** [test-network-function/test-network-function#583]
this is probably broken by #561

**Comment by jgato** [comment]
Looking about this issue, I have realized that I added some not need it extra code. The function getSuitesFromIdentifiers was added to get the Keys from the Catalogue map that I created, but this is no need it. It can be extracted during the for iteration. 
But this would provoke again an issue about sorting the output. I will take a look if I can make it sorted and not needing to extract the identifiers and iterate directly over the catalogue map.
